version: 2
jobs:
  build: 
    docker: 
      - image: circleci/postgres:9.6.5
        environment:
          db_user: advait
    steps:
      - run:
          name: Replacing Environment variable.
          environment:
            db_user: admin
      
      - run: echo ${db_user}
