version: 2.1
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: echo "In build job."
  
  deploy_docker:           
    docker:
      - image: alpine
    steps:
     - run: echo "deploy_docker section running"
     #- setup_remote_docker
      
      
workflows:
  workflow_1:
    jobs:
      - build
      - deploy_docker
