version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: echo "In build job."
  deploy_docker:           
    docker:
      - image: alpine
    steps:
     #- setup_remote_docker
      - run: echo "deploy_docker section running"
      
workflows:
  workflow_1:
    jobs:
      - build
      - deploy_docker
